spring:
  application:
    name: pet-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/pet
    username: admin
    password: admin
  threads:
    virtual:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    root: debug
