spring:
  web:
    resources:
      add-mappings: false
  application:
    name: pet-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/pet
    username: admin
    password: admin
  threads:
    virtual:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
#logging:
#  level:
#    root: debug

server:
  error:
    whitelabel:
      enabled: false
